services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5